language: node_js
node_js:
  - "stable"
env:
  - CI=false
branches:
  only:
  - master
before_install:
  - git config --global user.name "Travis CI"
  - git config --global user.email "deploy@travis-ci.org"
install:
  - yarn install
script:
  - yarn docs:build
after_success:
  - cd docs/.vuepress/dist
  - git init
  - git checkout --orphan gh-pages
  - git add -A
  - git commit -m "deploy docs"
  - git push --force https://$REPO_TOKEN@github.com/projectriri/bot-gateway.git gh-pages:gh-pages